CHANGES.rst, src/plone/rest/zcml.py
- Update title / description of `factory` attribute in service directive interface (was mentioning behaviors, but we have services)
- Remove `layer` attribute from service directive: we cannot support browser layers since we use the request discriminator for determining the request method (`IGET`, `IPOST`, `IPUT`..)
=> Update meta directive / drop request layer field

CHANGES.rst, README.rst, src/plone/rest/configure.zcml, src/plone/rest/demo.py, src/plone/rest/events.py, src/plone/rest/patches.py, src/plone/rest/service.py, src/plone/rest/testing.zcml, src/plone/rest/tests/test_dexterity.py, src/plone/rest/zcml.py
- Named services behave like browser views, thus we inherit from `P.Five.BrowserView`
to pass security checks in ZPublisher traversal.
- We flag API requests as non-WebDAV requests to avoid special treatment in
ZPublisher traversal which prevents named services to work with methods other than `GET`, `POST` and `PURGE`.
- Move marking of requests to IPubStart event as we need to set the non-WebDAV
flag before traversal starts.
(Also see discussion in #16)
=> Add support for named services.

CHANGES.rst, src/plone/rest/configure.zcml, src/plone/rest/errors.py, src/plone/rest/tests/test_error_handling.py
:grey_exclamation: base and target branch is `error-handling`  for inclusion in #13 :grey_exclamation: 
I've started implementing JSON error handling by providing an `index.html` adapter for exceptions.
This works quite well, but not for `Unauthorized` exceptions.
**1) Unauthorized is tricky**
The unauthorized exception is the only exception which is re-raised ([here](https://github.com/zopefoundation/Zope/blob/2.13.23/src/Zope2/App/startup.py#L231-L236)).
The exception is handled different than any other exceptions: mainly the PAS is asked and it leads to a redirect to the `login_form`.
I can suppress the redirect, but I'm unable to render non-HTML response since I'm not in control of that anymore.
My approach for fixing that is below, but it does not work, it only prevents redirecting: …
=> implement standard error handling.

src/plone/rest/testing.py, src/plone/rest/tests/test_error_handling.py
There are two definitions of the internal server error view used for testing error rendering.
This PR drops the one defined in `test_error_handling.py`, removes the corresponding `provideAdapter` calls (the other view is being registered in `testing.zcml`), and unifies naming.
@jone
=> Tests: Unify definition and use of internal server error view.

CHANGES.rst, src/plone/rest/patches.py, src/plone/rest/patches.zcml, src/plone/rest/tests/test_traversal.py
Before cleanup there were 3 patches doing the same for the portal root, Dexterity content and Archetypes content. Patching was done in the wrong place by adding additional pre-traversal hooks on these classes.
Now we patch the pre-traversal hook of `Products.CMFCore.DynamicType.DynamicType` directly which greatly simplifies the patch as the involved content classes all inherit from the `DynamicType` mixin.
The patch prevents appending the default view during traversal as this would break REST requests.
@lukasgraf 
/cc @tisto @bloodbare
=> Cleanup patch of DynamicType pre-traversal hook and add tests.

CHANGES.rst, src/plone/rest/configure.zcml, src/plone/rest/service.py, src/plone/rest/testing.py, src/plone/rest/testing.zcml, src/plone/rest/tests/test_traversal.py, src/plone/rest/traverse.py, src/plone/rest/zcml.py
As already discussed in #26 and probably experienced in #27 the current traversal implementation for REST services does not work in situations when another IPublishTraverse adapter takes precedence. 
Especially registering a service for a very unspecific context like
```
<plone:service
for="*"
name="search"
method="GET"
/>
```
will result in not working REST services because other traversal adapters are more specific for some contexts.
To address this issue i've reimplemented traversal for REST requests the following way:
- Implement a traversal adapter on the site root for REST requests
- Any traversed object is wrapped with a special traversal aware wrapper that handles further traversal
- Services no longer implement IPublishTraverse but are simple browser views.
- To make sure we do …
=> Traversal refactoring

CHANGES.rst, README.rst, src/plone/rest/events.py, src/plone/rest/negotiation.py, src/plone/rest/tests/test_negotiation.py, src/plone/rest/traverse.py, src/plone/rest/zcml.py
Acceptable media types for content negotiation can be configured in ZCML with the service directive.
Constraint: Only Accept headers with a single media type are considered candidates for API requests. Browsers often send an Accept header with multiple media types including wildcards. Evaluating all media types would result in unwanted matches.
There's still some JSON specific code left, that should be removed or adapted to work with other media types. This affects the `Service` base class and the `ErrorHandling` view.
Fixes #32
=> Implement content negotiation.

CHANGES.rst, src/plone/rest/events.py, src/plone/rest/interfaces.py, src/plone/rest/negotiation.py, src/plone/rest/tests/test_negotiation.py, src/plone/rest/zcml.py
The request method is now part of the adapter name though there's no longer the need for request method specific marker interfaces. This allows us to use the second discriminator for browser layers.
Fixes #17 
/cc @tisto @bloodbare @lukasgraf @jone
=> Add support for browser layers.

CHANGES.rst, src/plone/rest/interfaces.py, src/plone/rest/service.py, src/plone/rest/testing.zcml, src/plone/rest/tests/test_traversal.py, src/plone/rest/traverse.py
This allows us to override existing views with a named service (e.g. /search).
Fixes #42
=> Restrict traversal of REST requests to content objects.

CHANGES.rst, src/plone/rest/tests/test_dispatching.py
This adds a suite of **functional regression tests** to ensure service dispatching works as intended.
These tests simply assert on an expected HTTP status code for a number of cases, using an empty request body.
There are tests for all (sensible) combinations of
- Context (`SiteRoot`, `DX content`, `non-existent object`)
- HTTP Verbs (`GET`, `POST`, `PUT`, `PATCH`, `DELETE`, `OPTIONS`)
- Workflow state / required permissions (`public`, `private`)
- Authentication (`valid credentials`, `invalid credentials`, `no credentials`)
I intentionally did not use `for` loops to produce these combinations. IMHO it keeps the tests more expressive and readable, and makes it easier to see at a glance what the expected behavior for a particular case is.
This however means that there is a fair bit of …
=> Add regression tests for service dispatching.

CHANGES.rst, src/plone/rest/errors.py, src/plone/rest/tests/test_error_handling.py
Because their exception message gets turned into HTML by ZPublisher, we set a custom message for them instead of just serializing the exception's string representation.
Before:
```
{
"message": "  <h2>Site Error</h2>\n  <p>...</p>",
"type": "NotFound"
}
```
After:
```
{
"message": "Resource not found: http://localhost:8080/Plone/doesnt-exist",
"type": "NotFound"
}
```
Fixes #22
=> Improve message for 404 Not Found exceptions

CHANGES.rst, README.rst, src/plone/rest/service.py, src/plone/rest/testing.zcml, src/plone/rest/tests/test_dispatching.py, src/plone/rest/tests/test_permissions.py, src/plone/rest/zcml.py
Register services with the Zope configuration system instead of just registering an adapter. This provides better conflict detection and resolution.
Permission handling:
Currently the `permission` attribute is optional. This means that by default a service doesn't have a security declaration making it accessible for users that can access the underlying content object.
IMO we should make the `permission`attribute mandatory. However this will break current service definitions that don't already declare a permission. But as this concerns security, I think it's better if the user needs to declare a permission explicitly (same behavior as with browser views).
Opinions?
Fixes #36
=> Implement permission handling.

CHANGES.rst, README.rst, src/plone/rest/demo.py, src/plone/rest/service.py
As plone.rest supports arbitrary content types now, it no longer makes sense to render JSON in plone.rest.
We are moving this functionality into plone.restapi.
Fixes #46
=> Remove json rendering

CHANGES.rst, src/plone/rest/tests/test_traversal.py, src/plone/rest/traverse.py
This ensures compatiblity with existing views that are beeing called with a
specific Accept header.
Fixes #50
=> Fallback to regular views during traversal

CHANGES.rst, README.rst, src/plone/rest/errors.py, src/plone/rest/patches.py, src/plone/rest/patches.zcml, src/plone/rest/tests/test_dispatching.py, src/plone/rest/tests/test_redirects.py
`plone.rest` will now handle redirects created by [``plone.app.redirector``](https://github.com/plone/plone.app.redirector) pretty much the same way as regular Plone.
If a redirect exists for a given URL, a ``GET`` request will be answered with ``301``, and the new location for the resource is indicated in the ``Location`` header.
Any other request method than GET (``POST``, ``PATCH``, ...) will be answered with ``308 Permanent Redirect``. This status code instructs the client that it should NOT switch the method, but retry (if desired) the request the the *same* method at the new location.
Fixes #60
=> Add support for redirects from plone.app.redirector

CHANGES.rst, src/plone/rest/traverse.py
This way the package could be used on a zope installation
without the plone core
=> extract IPloneSiteRoot in favor of ISiteRoot

news/104.bugfix, src/plone/rest/zcml.py
This was the default for Bool fields until and including zope.schema 6.0.1.
In 6.1.0 this changed.
Since we have a default in the field definition, it does not look like any changes are needed for people using `plone.rest`.
Without this, we get errors like this on Jenkins with Plone coredev 6:
```
$ bin/test -s plone.rest
...
File "/Users/maurits/shared-eggs/cp38/zope.configuration-4.4.0-py3.8.egg
/zope/configuration/config.py", line 869, in finish
actions = self.handler(context, **args)
zope.configuration.xmlconfig.ZopeXMLConfigurationError:
File "/Users/maurits/community/plone-coredev/6.0/src/plone.rest/src/plone/rest/testing.zcml", line 163.2-167.6
TypeError: cors_policy_directive() missing 1 required positional argument: 'allow_credentials'
```
See …
=> Explicitly make allow_credentials required in CORS policy.

news/128.bugfix, src/plone/rest/tests/test_redirects.py, src/plone/rest/tests/test_traversal.py
Resolve all the deprecation warnings that originate in this package's code that are
exposed by running the tests.
=> test(deprecation): Fix all warnings from our code

news/132.fix, plone-5.2.x.cfg, src/plone/rest/errors.py, src/plone/rest/tests/test_redirects.py
This is a #130 follow-up.
The previous pull request fixes the redirect for content, but doesn't work for views (my fault, sorry). 
p.s I'm opening another PR about changing from 301 to safer 302 redirects, as in p.a.redirector (refs. https://github.com/plone/plone.app.redirector/issues/8 https://github.com/plone/plone.app.redirector/issues/22)
=> redirect with view

.gitignore, README.rst, news/135.bugfix, plone-4.3.x.cfg, plone-5.1.x.cfg, src/plone/rest/errors.py, src/plone/rest/tests/test_dispatching.py, src/plone/rest/tests/test_redirects.py
See motivation here:
https://github.com/plone/plone.app.redirector/issues/8
https://github.com/plone/plone.app.redirector/pull/22
https://github.com/plone/volto/issues/1095#issuecomment-693505028
=> Should redirection response be temporarily instead of permanent

news/162.bugfix, src/plone/rest/tests/test_traversal.py, src/plone/rest/traverse.py
Fixes #162 
@tisto I created a 3.x branch which is the target of this PR, since you didn't create one before starting to work on 4.x.
=> Fix compatibility with Python 2.7

news/168.bugfix, news/168.internal, src/plone/rest/tests/test_explicitacquisition.py
Before it would leak into other tests, enabling the publication check when it shouldn't be active.
=> Fixup tests: reset SKIP_PTA to whatever it was
